/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteNowRouteImport } from './routes/_site/now'
import { Route as SiteResumeRouteImport } from './routes/_site/resume'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardAssetsRouteImport } from './routes/_authenticated/dashboard.assets'
import { Route as AuthenticatedDashboardInboxRouteImport } from './routes/_authenticated/dashboard.inbox'
import { Route as AuthenticatedDashboardNowRouteImport } from './routes/_authenticated/dashboard.now'
import { Route as AuthenticatedDashboardResumeRouteImport } from './routes/_authenticated/dashboard.resume'
import { Route as AuthenticatedDashboardSeoRouteImport } from './routes/_authenticated/dashboard.seo'
import { Route as AuthenticatedDashboardSiteRouteImport } from './routes/_authenticated/dashboard.site'
import { Route as SiteProjectsIndexRouteImport } from './routes/_site/projects.index'
import { Route as SiteProjectsSlugRouteImport } from './routes/_site/projects.$slug'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as AuthenticatedDashboardProjectsIndexRouteImport } from './routes/_authenticated/dashboard.projects.index'
import { Route as AuthenticatedDashboardProjectsIdRouteImport } from './routes/_authenticated/dashboard.projects.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteNowRoute = SiteNowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteResumeRoute = SiteResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAssetsRoute =
  AuthenticatedDashboardAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInboxRoute =
  AuthenticatedDashboardInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNowRoute =
  AuthenticatedDashboardNowRouteImport.update({
    id: '/now',
    path: '/now',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardResumeRoute =
  AuthenticatedDashboardResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSeoRoute =
  AuthenticatedDashboardSeoRouteImport.update({
    id: '/seo',
    path: '/seo',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSiteRoute =
  AuthenticatedDashboardSiteRouteImport.update({
    id: '/site',
    path: '/site',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const SiteProjectsIndexRoute = SiteProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteProjectsSlugRoute = SiteProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardProjectsIndexRoute =
  AuthenticatedDashboardProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProjectsIdRoute =
  AuthenticatedDashboardProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/contact': typeof SiteContactRoute
  '/now': typeof SiteNowRoute
  '/resume': typeof SiteResumeRoute
  '/dashboard/assets': typeof AuthenticatedDashboardAssetsRoute
  '/dashboard/inbox': typeof AuthenticatedDashboardInboxRoute
  '/dashboard/now': typeof AuthenticatedDashboardNowRoute
  '/dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/dashboard/seo': typeof AuthenticatedDashboardSeoRoute
  '/dashboard/site': typeof AuthenticatedDashboardSiteRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/projects/': typeof SiteProjectsIndexRoute
  '/dashboard/projects/$id': typeof AuthenticatedDashboardProjectsIdRoute
  '/dashboard/projects/': typeof AuthenticatedDashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact': typeof SiteContactRoute
  '/now': typeof SiteNowRoute
  '/resume': typeof SiteResumeRoute
  '/dashboard/assets': typeof AuthenticatedDashboardAssetsRoute
  '/dashboard/inbox': typeof AuthenticatedDashboardInboxRoute
  '/dashboard/now': typeof AuthenticatedDashboardNowRoute
  '/dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/dashboard/seo': typeof AuthenticatedDashboardSeoRoute
  '/dashboard/site': typeof AuthenticatedDashboardSiteRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/projects': typeof SiteProjectsIndexRoute
  '/dashboard/projects/$id': typeof AuthenticatedDashboardProjectsIdRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_site': typeof SiteRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_site/contact': typeof SiteContactRoute
  '/_site/now': typeof SiteNowRoute
  '/_site/resume': typeof SiteResumeRoute
  '/_site/': typeof SiteIndexRoute
  '/_authenticated/dashboard/assets': typeof AuthenticatedDashboardAssetsRoute
  '/_authenticated/dashboard/inbox': typeof AuthenticatedDashboardInboxRoute
  '/_authenticated/dashboard/now': typeof AuthenticatedDashboardNowRoute
  '/_authenticated/dashboard/resume': typeof AuthenticatedDashboardResumeRoute
  '/_authenticated/dashboard/seo': typeof AuthenticatedDashboardSeoRoute
  '/_authenticated/dashboard/site': typeof AuthenticatedDashboardSiteRoute
  '/_site/projects/$slug': typeof SiteProjectsSlugRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_site/projects/': typeof SiteProjectsIndexRoute
  '/_authenticated/dashboard/projects/$id': typeof AuthenticatedDashboardProjectsIdRoute
  '/_authenticated/dashboard/projects/': typeof AuthenticatedDashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/dashboard'
    | '/contact'
    | '/now'
    | '/resume'
    | '/dashboard/assets'
    | '/dashboard/inbox'
    | '/dashboard/now'
    | '/dashboard/resume'
    | '/dashboard/seo'
    | '/dashboard/site'
    | '/projects/$slug'
    | '/api/admin/upload'
    | '/dashboard/'
    | '/projects/'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/contact'
    | '/now'
    | '/resume'
    | '/dashboard/assets'
    | '/dashboard/inbox'
    | '/dashboard/now'
    | '/dashboard/resume'
    | '/dashboard/seo'
    | '/dashboard/site'
    | '/projects/$slug'
    | '/api/admin/upload'
    | '/dashboard'
    | '/projects'
    | '/dashboard/projects/$id'
    | '/dashboard/projects'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_site'
    | '/auth'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_site/contact'
    | '/_site/now'
    | '/_site/resume'
    | '/_site/'
    | '/_authenticated/dashboard/assets'
    | '/_authenticated/dashboard/inbox'
    | '/_authenticated/dashboard/now'
    | '/_authenticated/dashboard/resume'
    | '/_authenticated/dashboard/seo'
    | '/_authenticated/dashboard/site'
    | '/_site/projects/$slug'
    | '/api/admin/upload'
    | '/_authenticated/dashboard/'
    | '/_site/projects/'
    | '/_authenticated/dashboard/projects/$id'
    | '/_authenticated/dashboard/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/now': {
      id: '/_site/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof SiteNowRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/resume': {
      id: '/_site/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof SiteResumeRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assets': {
      id: '/_authenticated/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof AuthenticatedDashboardAssetsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/inbox': {
      id: '/_authenticated/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof AuthenticatedDashboardInboxRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/now': {
      id: '/_authenticated/dashboard/now'
      path: '/now'
      fullPath: '/dashboard/now'
      preLoaderRoute: typeof AuthenticatedDashboardNowRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/resume': {
      id: '/_authenticated/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof AuthenticatedDashboardResumeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/seo': {
      id: '/_authenticated/dashboard/seo'
      path: '/seo'
      fullPath: '/dashboard/seo'
      preLoaderRoute: typeof AuthenticatedDashboardSeoRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/site': {
      id: '/_authenticated/dashboard/site'
      path: '/site'
      fullPath: '/dashboard/site'
      preLoaderRoute: typeof AuthenticatedDashboardSiteRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_site/projects/': {
      id: '/_site/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof SiteProjectsIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/projects/$slug': {
      id: '/_site/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof SiteProjectsSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/projects/': {
      id: '/_authenticated/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/projects/$id': {
      id: '/_authenticated/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAssetsRoute: typeof AuthenticatedDashboardAssetsRoute
  AuthenticatedDashboardInboxRoute: typeof AuthenticatedDashboardInboxRoute
  AuthenticatedDashboardNowRoute: typeof AuthenticatedDashboardNowRoute
  AuthenticatedDashboardResumeRoute: typeof AuthenticatedDashboardResumeRoute
  AuthenticatedDashboardSeoRoute: typeof AuthenticatedDashboardSeoRoute
  AuthenticatedDashboardSiteRoute: typeof AuthenticatedDashboardSiteRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardProjectsIdRoute: typeof AuthenticatedDashboardProjectsIdRoute
  AuthenticatedDashboardProjectsIndexRoute: typeof AuthenticatedDashboardProjectsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAssetsRoute: AuthenticatedDashboardAssetsRoute,
    AuthenticatedDashboardInboxRoute: AuthenticatedDashboardInboxRoute,
    AuthenticatedDashboardNowRoute: AuthenticatedDashboardNowRoute,
    AuthenticatedDashboardResumeRoute: AuthenticatedDashboardResumeRoute,
    AuthenticatedDashboardSeoRoute: AuthenticatedDashboardSeoRoute,
    AuthenticatedDashboardSiteRoute: AuthenticatedDashboardSiteRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardProjectsIdRoute:
      AuthenticatedDashboardProjectsIdRoute,
    AuthenticatedDashboardProjectsIndexRoute:
      AuthenticatedDashboardProjectsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SiteRouteRouteChildren {
  SiteContactRoute: typeof SiteContactRoute
  SiteNowRoute: typeof SiteNowRoute
  SiteResumeRoute: typeof SiteResumeRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProjectsSlugRoute: typeof SiteProjectsSlugRoute
  SiteProjectsIndexRoute: typeof SiteProjectsIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteContactRoute: SiteContactRoute,
  SiteNowRoute: SiteNowRoute,
  SiteResumeRoute: SiteResumeRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProjectsSlugRoute: SiteProjectsSlugRoute,
  SiteProjectsIndexRoute: SiteProjectsIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
